export const projectsData = [
    {
        id: 1,
        src: "/images/projects/work1-BigBazaar.jpg",
        category: "Website Design",
        title: "BIGBAZAAR.LK - ECOMMERCE",
    },
    {
        id: 2,
        src: "/images/projects/work2-Umar.jpg",
        category: "Website Design",
        title: "UMAR-HASSAN.COM - PERSONAL PORTFOLIO",
    },
    {
        id: 3,
        src: "/images/projects/work3-Techfusion.jpg",
        category: "Website Design",
        title: "TECHFUSIONSLAB.COM - COMPANY PORTFOLIO",
    },
    {
        id: 4,
        src: "/images/projects/work5-LMS.jpg",
        category: "Desktop Application",
        title: "LIBRARY MANAGEMENT SYSTEM - LMS",
    },
    {
        id: 5,
        src: "/images/projects/work4-BIM.jpg",
        category: "Website Design",
        title: "BOOK INVENTORY MANAGEMENT",
    },
    {
        id: 6,
        src: "/images/projects/work6-InvoiceAI.jpg",
        category: "AI Application",
        title: "INVOICE AI - FINAL YEAR PROJECT"
    },
    {
        id: 7,
        src: "/images/projects/No-Content.jpg",
        category: "Branding",
        title: "Bigbazaar.lk - Logo Design",
    },
    {
        id: 8,
        src: "/images/projects/No-Content.jpg",
        category: "Social Media Post Design",
        title: "Bigbazaar.lk - Facebook Post Design",
    },
    {
        id: 9,
        src: "/images/projects/No-Content.jpg",
        category: "Social Media Post Design",
        title: "Egrow.lk - Facebook Post Design",
    },
    {
        id: 10,
        src: "/images/projects/No-Content.jpg",
        category: "Logo Design",
        title: "TechFusionsLab.com - Logo Design",
    },
    // {
    //     id: 11,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: "Sentry, Los Angeles - Logo Design",
    // },
    // {
    //     id: 12,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: "Femme House - Logo Design",
    // },
    // { id: 13,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: "AIFA NIHON, Japan - Logo Design",
    // },
    // {
    //     id: 14,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: "Haldi Fashion - Logo Design",
    // },
    // {
    //     id: 15,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: "Uniqlo Galgamuwa - Logo Design",
    // },
    // {
    //     id: 16,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: " Osaka Auto Mart, Japan - Logo Design",
    // },
    // {
    //     id: 17,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: "Kitchen Max - Logo Design",
    // },
    // {
    //     id: 18,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: " The Mug Mania - Logo Design",
    // },
    // {
    //     id: 19,
    //     src: "/images/projects/No-Content.jpg",
    //     category: "Logo Design",
    //     title: "EDF Galgamuwa - Logo Design",
    // },
]
